PROGRAM_NAME = 'mesothelae'

MESSAGE_DATABASE_NAME = PROGRAM_NAME + 'MessageDatabase'
MESSAGE_DATABASE_FILE_NAME = f'/var/wpd/{PROGRAM_NAME}/messages.json'
MESSAGE_DATABASE_FILE_NAME = 'messages.json'

USER_DATABASE_NAME = PROGRAM_NAME + 'UserDatabase'
USER_DATABASE_FILE_NAME = f'/var/wpd/{PROGRAM_NAME}/users.json'
USER_DATABASE_FILE_NAME = 'users.json'