from enum import Enum, unique

@unique
class StatusCode(Enum):
    OK = 'OK'

    # Warnings
    INVALID_REQUEST = 'INVALID_REQUEST'
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS'
    INVALID_SESSION_ID = 'INVALID_SESSION_ID'
    USERNAME_NOT_UNIQUE = 'USERNAME_NOT_UNIQUE'

    # Errors:
    UNKNOWN_ERROR = 'UNKNOWN_ERROR'
    DATABASE_READ_ERROR = 'DATABASE_READ_ERROR'
    DATABASE_CORRUPTED = 'DATABASE_CORRUPTED'